  version: 2
  updates:
    - package-ecosystem: github-actions
      rebase-strategy: disabled
      directory: /
      assignees:
        - dshoreman
      reviewers:
        - dshoreman
      schedule:
        interval: weekly
