os: linux
dist: bionic
language: php

services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

jobs:
  include:
    - php: 7.4
      env: RUN_MODE=php
    - php: 8.0
      env: RUN_MODE=php-latest

before_install:
  - phpenv config-rm xdebug.ini

install:
  - .github/scripts/install.sh

before_script:
  - .github/scripts/prepare.sh

script:
  - .github/scripts/script.sh

after_failure:
  - cat storage/logs/laravel.log

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  irc:
    channels:
      - "chat.freenode.net#servidor"
    on_success: change
    on_failure: always
    template:
      - "Build #%{build_number} (%{branch} @ %{commit} by %{author}) - %{message}"
      - "Details: %{build_url}"
