on: [push, pull_request]

jobs:
  build-js:
    name: Frontend (nodejs-${{ matrix.nodejs }} on ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    env:
      CI_NODE_VERSION: ${{ matrix.nodejs }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        nodejs: [12, 14]
    steps:
      - uses: actions/checkout@v2
      - name: Setup NodeJS Environment
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.nodejs }}
      - name: NPM node_modules cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: npm-${{ matrix.os }}-node${{ matrix.nodejs }}-${{ hashFiles('package-lock.json') }}
      - name: Install npm modules
        run: npm clean-install
      - name: Build frontend assets
        run: npm run prod
      - name: Run ESLint
        run: make eslint

  test-php:
    name: Backend (php-${{ matrix.php }} on ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    env:
      RUN_MODE: php
      CI_PHP_VERSION: ${{ matrix.php }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
        php: ['7.4', '8.0']
        experimental: [false]
        include:
          - php: '8.1'
            os: ubuntu-20.04
            experimental: true
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Setup PHP Environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: pcov
      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"
      - name: Composer vendor cache
        uses: actions/cache@v1
        with:
          path: vendor
          key: composer-${{ matrix.os }}-php${{ matrix.php }}-${{ hashFiles('composer.lock') }}
      - name: Install application
        run: bash .github/scripts/install.sh
      - name: Lint and Test
        run: bash .github/scripts/script.sh
      - name: Upload coverage results
        uses: codecov/codecov-action@v1
      - name: Check Laravel log
        if: failure()
        run: test -f storage/logs/laravel.log && cat storage/logs/laravel.log
