on: [push, pull_request]

jobs:
  test-php:
    name: Backend/API (PHP${{ matrix.php }} on ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    env:
      RUN_MODE: php
      CI_PHP_VERSION: ${{ matrix.php }}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-2019]
        php: ['7.4', '8.0']
        experimental: [false]
        fail-fast: false
        include:
          - php: '8.0'
            experimental: true
          - os: windows-2019
            experimental: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP Environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: pcov
      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"
      - name: Composer vendor cache
        uses: actions/cache@v1
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}
      - name: Install application
        run: .github/scripts/install.sh
      - name: Prepare permissions
        run: .github/scripts/prepare.sh
      - name: Lint and Test
        run: .github/scripts/script.sh
      - name: Upload coverage results
        uses: codecov/codecov-action@v1
      - name: Print Laravel logs on failure
        if: failure()
        run: cat storage/logs/laravel.log

  build-js:
    name: Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: NPM node_modules cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: npm-${{ hashFiles('package-lock.json') }}
      - name: Install npm modules
        run: npm clean-install
      - name: Build frontend assets
        run: npm run prod
      - name: Run ESLint
        run: make eslint
