on: [push, pull_request]

jobs:
  build-js:
    name: Lint frontend (nodejs-${{ matrix.nodejs }} on ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        nodejs: [12, 14]
    steps:
      - uses: actions/checkout@v2
      - name: Setup NodeJS Environment
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.nodejs }}
      - name: NPM node_modules cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: npm-${{ matrix.os }}-node${{ matrix.nodejs }}-${{ hashFiles('package-lock.json') }}
      - name: Install npm modules
        run: npm clean-install
      - name: Build frontend assets
        run: npm run prod
      - name: Run ESLint
        run: make eslint

  lint-php:
    name: Lint PHP
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Validate composer.json and lockfile
        run: composer validate
      - name: Install composer packages
        run: composer install --no-interaction --no-progress --prefer-dist
      - name: Run PHP CS Fixer
        run: make phpcsf CS_ARGS="--verbose"
      - name: Check PSR12 compliance
        run: make phpcs
      - name: Run PHP Mess Detector
        run: make phpmd
      - name: Detect magic numbers
        run: make phpmnd MND_ARGS="--non-zero-exit-on-violation"
      - name: Run PHPStan checks
        run: make phpstan
      - name: Run Psalm checks
        run: make psalm

  test-php:
    needs: lint-php
    name: Test Backend (php-${{ matrix.php }} on ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
        php: ['7.4', '8.0']
        experimental: [false]
        include:
          - php: '8.1'
            os: ubuntu-20.04
            experimental: true
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Setup PHP Environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: pcov
      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"
      - name: Composer vendor cache
        uses: actions/cache@v1
        with:
          path: vendor
          key: composer-${{ matrix.os }}-php${{ matrix.php }}-${{ hashFiles('composer.lock') }}
      - name: Install application
        run: bash .github/scripts/install.sh
      - name: Run tests with PHPUnit
        run: make test-for-ci
      - name: Upload coverage results
        uses: codecov/codecov-action@v1
      - name: Check Laravel log
        if: failure()
        run: test -f storage/logs/laravel.log && cat storage/logs/laravel.log
