on: [push, pull_request]

jobs:
  build-js:
    name: Lint frontend (nodejs-${{ matrix.nodejs }} on ${{ matrix.os }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nodejs: [12, 14]
    steps:
      - uses: actions/checkout@v2
      - name: Setup NodeJS Environment
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.nodejs }}
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-node${{ matrix.nodejs }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: npm-node${{ matrix.nodejs }}-
      - name: Install npm modules
        uses: nick-invision/retry@v2
        with:
          timeout_seconds: 45
          max_attempts: 3
          command: npm clean-install
      - name: Build frontend assets
        run: npm run prod
      - name: Run ESLint
        run: make eslint

  lint-php:
    name: Lint PHP
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Validate composer.json and lockfile
        run: composer validate
      - uses: actions/cache@v2
        id: composer-lint-cache
        with:
          path: ~/.cache/composer/files
          key: composer-php8.0-${{ hashFiles('**/composer.lock') }}
          restore-keys: composer-php8.0-
      - name: Install composer packages
        uses: nick-invision/retry@v2
        with:
          timeout_seconds: 45
          max_attempts: 3
          command: composer install --no-interaction --no-progress --prefer-dist
      - name: Run PHP CS Fixer
        run: make phpcsf CS_ARGS="--verbose"
      - name: Check PSR12 compliance
        run: make phpcs
      - name: Run PHP Mess Detector
        run: make phpmd
      - name: Detect magic numbers
        run: make phpmnd MND_ARGS="--non-zero-exit-on-violation"
      - name: Run PHPStan checks
        run: make phpstan
      - name: Run Psalm checks
        run: make psalm

  test-php:
    if: always()
    needs: lint-php
    name: Test Backend (php-${{ matrix.php }} on ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
        php: ['7.4', '8.0']
        experimental: [false]
        include:
          - php: '8.1'
            os: ubuntu-latest
            experimental: true
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Setup PHP Environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: pcov
      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"
      - uses: actions/cache@v2
        id: composer-test-cache
        with:
          path: ~/.cache/composer/files
          key: composer-php${{ runner.php }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: composer-php${{ runner.php }}-
      - name: Install composer packages
        uses: nick-invision/retry@v2
        with:
          timeout_seconds: 45
          max_attempts: 3
          command: composer install --no-interaction --no-progress --prefer-dist
      - name: Install application
        run: bash .github/scripts/install.sh
      - name: Run tests with PHPUnit
        run: make test-for-ci
      - name: Upload coverage results
        uses: codecov/codecov-action@v1
      - name: Check Laravel log
        if: failure()
        run: test -f storage/logs/laravel.log && cat storage/logs/laravel.log

  notify:
    if: always()
    name: Send IRC Notification
    needs: [build-js, test-php]
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/workflow-conclusion-action@v2
      - name: Send failure notification
        uses: rectalogic/notify-irc@v1
        with:
          channel: '#servidor'
          nickname: 'servidor-bot'
          message: |-
            ${{ github.event.ref }} pushed to by ${{ github.actor }} (status: ${{ env.WORKFLOW_CONCLUSION }}) - ${{ github.event.compare }}
